### ISSUE TITLE
RNA documentation for v10

### ISSUE THREAD

**Issue by taylordm** [PediatricOpenTargets/documentation#1]
We need a document, about 2 pages, for RNA-seq documentation for outside individuals. It should try to do as much linking out to primary documentation as possible. 

It should include information on how we derived all quantified RNA-seq analysis results, including fusion results on the MTP page.

**Comment by kelseykeith** [comment]
Closed with completion of main v10 documentation <https://github.com/PediatricOpenTargets/documentation/blob/1fa628f8b36e976a372945952cd5791c5fde4962/README.md>
